# GRAY INTERFACE 

## HackSlash 

----

# NumPy

## Exercise 1: Creating Numpy arrays

----

#### Write & Run CODE to answer each of the given problem statement.
##### Note that Sample Output of the problem statement is also given for reference. 

----

## Import numpy

In [2]:
import numpy as np

## Create Numpy arrays from Python list


#### Create Numpy 1d array from list

`array([1, 2, 3])`

In [ ]:
list_1d = np.array[1,2,3]

In [ ]:
list_1d

[1, 2, 3]

#### Create Numpy 2d array from list

`array([[1, 2, 3],
       [4, 5, 6]])`

In [ ]:
list_2d = np.array([[1,2,3],
                   [4,5,6]])

In [ ]:
list_2d

array([[1, 2, 3],
       [4, 5, 6]])

#### Create Numpy 3d array from list

`array([[[1, 2, 3],
        [4, 5, 6]],
       [[1, 2, 3],
        [4, 5, 6]]])`

In [ ]:
list_3d = np.array([[[1,2,3],
                     [4,5,6]], 
                    [[1,2,3],
                     [4,5,6]]])

In [ ]:
list_3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

-----

## Create Numpy arrays using functions

#### Create a Numpy 1d array of 10 zeros 

 `array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])`

In [ ]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create a Numpy 1d array of 10 ones

`array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])`

In [ ]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create a Numpy 1d array of 10 fives

`array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])`

In [ ]:
fives = ones*5
fives.astype(int)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create a Numpy 1d array consisting of all the integers from 10 to 50

`array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])`

In [ ]:
a1 = np.arange(10, 50)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create a Numpy 1d array consisting of all the even integers only from 10 to 50

`array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])`

In [ ]:
a2 = np.arange(10, 50, 2)
a2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a Numpy 2d array with shape (3,3) having all entries as 1

`array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])`

In [ ]:
a3 = np.ones((3,3))
a3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Create a Numpy 2d array with shape (10,10) having all diagonal entries as 1 and all others as 0

`array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])`

In [ ]:
a4 = np.zeros((10, 10))
np.fill_diagonal(a4, 1)
a4

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### Create a Numpy 2d array with shape (5,6) consisting of values ranging from 1 to 30

`array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])`

In [ ]:
a5 = np.arange(1, 31).reshape(5, 6)
a5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

#### Create a Numpy 1d array consisting of a random number between 0 and 1

`array([0.42829726])`

In [ ]:
a6 = np.random.random(1)
a6

array([0.07729339])

#### Create a Numpy 1d array consisting of six *random* numbers between 0 and 1

`array([0.48986417, 0.61869789, 0.83943457, 0.94889576, 0.79561515, 0.28859058])`

In [ ]:
a7 = np.random.random(6)
a7

array([0.31603255, 0.94442351, 0.67546733, 0.49993517, 0.12707087,
       0.49862089])

#### Create a Numpy 2d array of shape (2,3) consisting of five *random* numbers between 0 and 1

`array([[0.3991418 , 0.62631826, 0.82763635],
       [0.9232742 , 0.08517427, 0.20155819]])`

In [ ]:
a8 = np.random.random(size=(2, 3))
a8

array([[0.39039111, 0.82852577, 0.76315103],
       [0.82700325, 0.08247063, 0.13188691]])

#### Create a Numpy 1d array consisting of 25 random numbers sampled from a *Standard Normal Distribution*

`array([-0.01804177, -0.11468092, -0.4790744 , -0.44706856,  0.49891779,
        1.53806364, -1.03689237,  0.04379123, -0.6659274 , -0.54294319,
       -0.08016372, -0.64441992, -0.12417271,  0.89901988, -0.08695241,
        0.23540321,  1.77803936,  1.39912268,  0.19886053, -0.56546787,
        0.09538678, -0.47930312,  2.15532489,  0.62643712,  1.19941788])`

In [ ]:
a9 = np.random.normal(0, 1, 25)
a9

array([-1.28311083, -0.51166075, -1.16968094,  1.40954369,  0.69034305,
       -1.24372526, -0.27167964,  0.62141372, -1.49565467, -0.45851534,
        0.36675755,  0.7458972 ,  0.2076125 ,  1.4570458 , -0.2218839 ,
       -1.38782674, -1.85398042, -0.45296259,  0.91931724,  0.12496521,
       -1.27608387, -0.60804623,  0.43132898, -1.44829818, -0.73356109])

#### Generate a *random* integer between 1 and 50

`32`

In [ ]:
a10 = np.random.randint(1, 50)
a10

36

#### Create a Numpy 1d array consisting of five *random* integers between 1 and 50

`array([36, 30, 32, 14,  2])`

In [ ]:
a11 = np.random.randint(1, 50, size=(5))
a11

array([41, 43, 23, 28, 14])

#### Create a Numpy array consisting of 20 linearly spaced points between 0 and 1

`array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])`

In [3]:
a12 = np.linspace(0, 1, num=20)
a12

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Create the following Numpy 2d array:

`array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])`

In [ ]:
a13 = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
a13

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

-----

# Great Job!